In [1]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\gebruikerr\desktop\lib\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in c:\users\gebruikerr\desktop\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
import pandas as pd
import numpy as np
# Read Excel file
df = pd.read_excel('Dealroom2.xlsx', usecols=['NAME', 'HQ COUNTRY', 'INVESTORS', 'TOTAL FUNDING (EUR M)', 'LAUNCH YEAR', 'INDUSTRIES', 'EMPLOYEES', 'PROFIT (2016,2017,2018,2019,2020,2021,2022,2023,2024)', 'FOUNDERS'])
#NAME, COUNTRY, INVESTORS, TOTAL FUNDING, LAUNCH YEAR, INDUSTRIES, EMPLOYEES, PROFIT, FOUNDERS
df.rename(columns = {'PROFIT (2016,2017,2018,2019,2020,2021,2022,2023,2024)':'PROFIT', 'TOTAL FUNDING (EUR M)':'TOTAL FUNDING'}, inplace = True)


# Remove the 'PROFIT' column from the original DataFrame 'df'
#df.drop('PROFIT', axis=1, inplace=True)

# Append the 'MEAN' column from df2 to 'df'
#df['MEAN'] = df2['MEAN']
#replace NaN with 0
df = df.fillna(0)



display(df)

,NAME,HQ COUNTRY,INVESTORS,TOTAL FUNDING,LAUNCH YEAR,INDUSTRIES,EMPLOYEES,PROFIT,FOUNDERS
0,Bigdash,Netherlands,0,0.00,2007.0,enterprise software,'1,n/a;n/a;n/a;n/a;n/a;;;n/a;n/a,Willem Overbosch
1,Globalinter.net,Netherlands,Expereo,0.00,2012.0,telecom,'11-50,n/a;;n/a;3375311;698017;n/a;n/a;n/a;n/a,0
2,Bundleboon,Netherlands,Pieter Schoen;Startupbootcamp;Startupbootcamp ...,4.50,2017.0,fashion;kids,'2-10,n/a;n/a;n/a;n/a;n/a;n/a;n/a;n/a;n/a,Michel Ariens
3,Julius Clinical,Netherlands,0,0.00,2008.0,health,'51-200,2166178;2755914;-3559867;-3464136;n/a;n/a;n/a;...,Peter Schoevers
4,Creative Clicks,Netherlands,Pieter Schoen;VOC Capital Partners;Shoe Invest...,0.00,2009.0,marketing,'51-200,13227748;6422066;6257948;2254245;5635356;14882...,Ramon van den Bulk
...,...,...,...,...,...,...,...,...,...
995,DB2 Vision,Netherlands,0,0.00,2016.0,food,'2-10,n/a;n/a;n/a;n/a;n/a;n/a;n/a;n/a;n/a,Igno Breukers
996,Yandex Data Factory,Netherlands,Yandex,0.00,2014.0,security;enterprise software,'2-10,n/a;n/a;n/a;n/a;n/a;n/a;n/a;n/a;n/a,Oleg Koverznev
997,Reboocon Bionics,Netherlands,YES!Delft,0.00,2016.0,health;robotics,'11-50,n/a;n/a;n/a;n/a;n/a;n/a;n/a;n/a;n/a,Shiqian Wang
998,SOURCE,Netherlands,E14 Fund;Acre Venture Partners;Astanor Venture...,33.64,2020.0,food,'51-200,n/a;n/a;n/a;n/a;n/a;n/a;;;n/a,Rien Kamman;Ernst Van Bruggen
999,Rebottled,Netherlands,0,0.00,2017.0,food;energy,'2-10,n/a;n/a;n/a;n/a;n/a;n/a;n/a;n/a;n/a,Jermain Graaf

In [13]:
#ATTEMPT 1
#df2= pd.concat([df[['PROFIT (2016,2017,2018,2019,2020,2021,2022,2023,2024)']], df[1].str.split('; ', expand=True)], axis=1)
#df2 = df['PROFIT'].str.split(';', expand=True)
#df2 = df['PROFIT'].str.replace('n/a', '0')

#df2 = df2.apply(pd.to_numeric)
#avg = df2.mean(axis=1)


#avg= df2.mean(axis=1, numeric_only=True)
#display(df2)
#print(avg)

In [9]:
%pip install tabulate

Collecting tabulate
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Installing collected packages: tabulate
Successfully installed tabulate-0.9.0
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script tabulate.exe is installed in 'c:\Users\gebruikerr\Desktop\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [18]:
import pandas as pd
from tabulate import tabulate


#split og data by ;
df2 = df['PROFIT'].str.split(';', expand=True)

#replace n/a values
df2 = df2.apply(lambda x: x.str.replace('n/a', '0')).apply(pd.to_numeric)

#find mean
avg = df2.mean(axis=1)
df2['MEAN'] = avg

#replace NaN values with fillna
df2 = df2.fillna(0)

#rename columns for clarity
df2.columns = ['2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', 'MEAN']

#make it look good using tabulate
table= tabulate(df2, headers='keys', tablefmt='pretty', showindex=False)

print(table)

+-------------+-------------+-------------+-------------+-------------+-------------+--------------+-------------+-------------+---------------------+
|    2016     |    2017     |    2018     |    2019     |    2020     |    2021     |     2022     |    2023     |    2024     |        MEAN         |
+-------------+-------------+-------------+-------------+-------------+-------------+--------------+-------------+-------------+---------------------+
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |  3375311.0  |  698017.0   |     0.0     |     0.0      |     0.0     |     0.0     |      509166.0       |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  2166178.0  |  2755914.0  | -3559867.0  | -3464136.0  |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     | -233545.66666666666 |
| 13227748.0  |  6422066.0  |  6257948.0  |  2254245.0  |  5635356.0  | 14882776.0  |     0.0      |     0.0     |     0.0     |  6954305.571428572  |
|     0.0     |     0.0     |     0.0     |     0.0     |  -333732.0  |  1493779.0  |     0.0      |     0.0     |     0.0     | 128894.11111111111  |
| 10495891.0  |  8624502.0  | 10211978.0  | 12672249.0  | 13099771.0  |  8270098.0  |  16145730.0  |     0.0     |     0.0     |     9940027.375     |
|     0.0     |     0.0     |     0.0     |     0.0     |  613000.0   |     0.0     |     0.0      |     0.0     |     0.0     |  68111.11111111111  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |  179000.0   |  334000.0   |  283000.0   |  -321000.0  |  1913000.0  |     0.0      |     0.0     |     0.0     | 341142.85714285716  |
|  1313228.0  |  1720254.0  |  2372376.0  |  2746944.0  |  3061582.0  |     0.0     |     0.0      |     0.0     |     0.0     | 1246042.6666666667  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  -107407.0  |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     | -11934.111111111111 |
|  1347593.0  |  1196528.0  |  838774.0   |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     | 375877.22222222225  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  1783975.0  |  2641086.0  |  3127449.0  |  2284561.0  |  3763011.0  |     0.0     |     0.0      |     0.0     |     0.0     | 1511120.2222222222  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  4807982.0  |  3656699.0  |  4165488.0  |  3655056.0  |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     | 2714204.1666666665  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  2278913.0  |  -471836.0  |     0.0     |     0.0     | -11280533.0 | -13100770.0 |     0.0      |     0.0     |     0.0     | -3224889.4285714286 |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  3498428.0  |  3364292.0  |  3556773.0  |  2931068.0  |  6204551.0  |  6625069.0  |     0.0      |     0.0     |     0.0     |     3272522.625     |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |  2196687.0  |  1163442.0  |     0.0      |     0.0     |     0.0     |  480018.4285714286  |
|  383307.0   |  -896342.0  |  -783181.0  | -2695864.0  | -3083155.0  | -4078869.0  |     0.0      |     0.0     |     0.0     |     -1394263.0      |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     | -2144885.0  | -1984223.0  |     0.0     |  3766000.0  |  2682000.0   |     0.0     |     0.0     |      289861.5       |
|     0.0     |  221534.0   |  554454.0   |  1107797.0  |  642974.0   |  758014.0   |   822300.0   |     0.0     |     0.0     | 456341.44444444444  |
|  796253.0   |  1157138.0  |  1088864.0  |  302783.0   |  461939.0   |  2943784.0  |  1292670.0   |     0.0     |     0.0     |  893714.5555555555  |
|     0.0     |     0.0     |     0.0     | -3834018.0  |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |      -426002.0      |
|     0.0     |   12098.0   |   53789.0   |  183514.0   |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     | 41566.833333333336  |
|  -189354.0  |  -137102.0  |  -35553.0   |   87986.0   |   46088.0   |   56475.0   |   34017.0    |     0.0     |     0.0     | -15271.444444444445 |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  813831.0   |  824063.0   |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |      409473.5       |
|  1527457.0  |  1361649.0  |  807759.0   |  896713.0   |  1558333.0  |     0.0     |     0.0      |     0.0     |     0.0     |  683545.6666666666  |
|  4880871.0  |     0.0     |     0.0     |  1863430.0  |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |  749366.7777777778  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |  2744344.0  |  3898324.0  |  4223926.0  |     0.0      |     0.0     |     0.0     | 1207399.3333333333  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  295259.0   |  -741026.0  |   43819.0   | 21034267.0  |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     | 3438719.8333333335  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  4404071.0  |  2288854.0  |  1154816.0  |  1952022.0  | -3161140.0  |  1534897.0  |  5308924.0   |     0.0     |     0.0     | 1498049.3333333333  |
| -1556960.0  | -1567848.0  |  -373454.0  |  1712536.0  |  3684620.0  |  7001949.0  |  7160238.0   |     0.0     |     0.0     |     2007635.125     |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  1466000.0  |  4288000.0  |  5717000.0  |  6519000.0  |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |  1998888.888888889  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  5548763.0  |     0.0     |  2102680.0  |  2129027.0  |  4900691.0  |  3235700.0  |  2838162.0   |     0.0     |     0.0     | 2306113.6666666665  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |  1150402.0  |  1541437.0  |     0.0     |     0.0      |     0.0     |     0.0     | 299093.22222222225  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |  103344.0   |  324643.0   |  849459.0   |  578858.0   |     0.0      |     0.0     |     0.0     |      206256.0       |
|     0.0     |     0.0     |     0.0     |  1316839.0  |  1227128.0  |     0.0     |     0.0      |     0.0     |     0.0     |      282663.0       |
|     0.0     |     0.0     |  -251000.0  |  -245000.0  |  -125000.0  |  -88000.0   |   -92000.0   |     0.0     |     0.0     |      -100125.0      |
|     0.0     |     0.0     |  9513746.0  | 12891278.0  |  5260654.0  |     0.0     |     0.0      |     0.0     |     0.0     |  3952239.714285714  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |  -85363.0   | -1014268.0  |  -669597.0  |  -438296.0  |  295680.0   |   35680.0    |     0.0     |     0.0     |      -234520.5      |
|  1258378.0  |  723962.0   |     0.0     |     0.0     |  -348720.0  |  -382934.0  |   107361.0   |     0.0     |     0.0     | 226341.16666666666  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  344415.0   |  -895288.0  |  426094.0   |  198445.0   |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |       14733.2       |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |  259708.0   |  790228.0   |  159704.0   |  440395.0   |     0.0      |     0.0     |     0.0     | 183337.22222222222  |
|     0.0     |  256173.0   |  184757.0   |   37184.0   |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |  79685.66666666667  |
|     0.0     |  2228530.0  |  1838423.0  | -1960277.0  | -3953042.0  | -1571933.0  |     0.0      |     0.0     |     0.0     |      -379811.0      |
|   -1440.0   |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |       -160.0        |
|  7032506.0  | 10005079.0  |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |      5679195.0      |
|   -253.0    |    -76.0    |  -272000.0  |  133000.0   |  -518000.0  |  -428000.0  |  -164000.0   |     0.0     |     0.0     | -138814.33333333334 |
|  3777971.0  |  3680747.0  |  3845937.0  |  6035516.0  |  8525697.0  | 10582800.0  |     0.0      |     0.0     |     0.0     |  5206952.571428572  |
|   -4091.0   |   4367.0    |   2618.0    |   2516.0    |   -5921.0   |   4728.0    |    7890.0    |     0.0     |     0.0     |      1513.375       |
|  821758.0   |  1196579.0  |  1433152.0  |  1402920.0  |  1981898.0  |  2401694.0  |     0.0      |     0.0     |     0.0     | 1026444.5555555555  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |  7786692.0  |  3310664.0  |  7062538.0  | 31558167.0  | 11170707.0  |     0.0      |     0.0     |     0.0     |  8698395.42857143   |
|     0.0     | -6374000.0  | -6130000.0  | -8534000.0  | -9887000.0  | -7703000.0  |     0.0      |     0.0     |     0.0     | -5518285.714285715  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |  2570633.0  |  2309892.0  |  2823251.0  |  2351185.0   |     0.0     |     0.0     |  1117217.888888889  |
|     0.0     |     0.0     |     0.0     |  1370802.0  |  3667366.0  |  7099541.0  |     0.0      |     0.0     |     0.0     | 1348634.3333333333  |
|  3439372.0  |  5025923.0  |  5328839.0  |  6644768.0  |  6436000.0  |     0.0     |     0.0      |     0.0     |     0.0     |  2986100.222222222  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  2075638.0  |  2007501.0  |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |  453682.1111111111  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  779083.0   |  1425238.0  |  1282211.0  |  1489860.0  |  1606158.0  |  5830944.0  |     0.0      |     0.0     |     0.0     |  1379277.111111111  |
|  3297912.0  |  6455330.0  |     0.0     |     0.0     | 25398366.0  | 15014765.0  |     0.0      |     0.0     |     0.0     |     10033274.6      |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|  3575000.0  |  5248000.0  |  5164000.0  |  5892000.0  |  7757000.0  |  8497000.0  |     0.0      |     0.0     |     0.0     |  5161857.142857143  |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |
|     0.0     |     0.0     | 20498000.0  | 58295000.0  |  5791000.0  |  5061000.0  |  -822000.0   |     0.0     |     0.0     |     11102875.0      |
|     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0     |     0.0      |     0.0     |     0.0     |         0.0         |

In [19]:
# Read Excel file
df = pd.read_excel('Dealroom2.xlsx', usecols=['NAME', 'HQ COUNTRY', 'INVESTORS', 'TOTAL FUNDING (EUR M)', 'LAUNCH YEAR', 'INDUSTRIES', 'EMPLOYEES', 'PROFIT (2016,2017,2018,2019,2020,2021,2022,2023,2024)', 'FOUNDERS'])
#NAME, COUNTRY, INVESTORS, TOTAL FUNDING, LAUNCH YEAR, INDUSTRIES, EMPLOYEES, PROFIT, FOUNDERS
df.rename(columns = {'PROFIT (2016,2017,2018,2019,2020,2021,2022,2023,2024)':'PROFIT', 'TOTAL FUNDING (EUR M)':'TOTAL FUNDING'}, inplace = True)


# Remove the 'PROFIT' column from the original DataFrame 'df'
df.drop('PROFIT', axis=1, inplace=True)

# Append the 'MEAN' column from df2 to 'df'
df['MEAN'] = df2['MEAN']

#replace NaN with 0
df = df.fillna(0)


display(df)

,NAME,HQ COUNTRY,INVESTORS,TOTAL FUNDING,LAUNCH YEAR,INDUSTRIES,EMPLOYEES,FOUNDERS,MEAN
0,Bigdash,Netherlands,0,0.00,2007.0,enterprise software,'1,Willem Overbosch,0.000000e+00
1,Globalinter.net,Netherlands,Expereo,0.00,2012.0,telecom,'11-50,0,5.091660e+05
2,Bundleboon,Netherlands,Pieter Schoen;Startupbootcamp;Startupbootcamp ...,4.50,2017.0,fashion;kids,'2-10,Michel Ariens,0.000000e+00
3,Julius Clinical,Netherlands,0,0.00,2008.0,health,'51-200,Peter Schoevers,-2.335457e+05
4,Creative Clicks,Netherlands,Pieter Schoen;VOC Capital Partners;Shoe Invest...,0.00,2009.0,marketing,'51-200,Ramon van den Bulk,6.954306e+06
...,...,...,...,...,...,...,...,...,...
995,DB2 Vision,Netherlands,0,0.00,2016.0,food,'2-10,Igno Breukers,0.000000e+00
996,Yandex Data Factory,Netherlands,Yandex,0.00,2014.0,security;enterprise software,'2-10,Oleg Koverznev,0.000000e+00
997,Reboocon Bionics,Netherlands,YES!Delft,0.00,2016.0,health;robotics,'11-50,Shiqian Wang,0.000000e+00
998,SOURCE,Netherlands,E14 Fund;Acre Venture Partners;Astanor Venture...,33.64,2020.0,food,'51-200,Rien Kamman;Ernst Van Bruggen,0.000000e+00
999,Rebottled,Netherlands,0,0.00,2017.0,food;energy,'2-10,Jermain Graaf,0.000000e+00

In [ ]:
d = {'col1': [0, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
display(df)
avg= df.mean(axis=1, numeric_only=True)
print(avg)

   col1  col2
0     0     3
1     2     4

0    1.5
1    3.0
dtype: float64