Cleaning DNNL Data

In [89]:
import pandas as pd
import string

#Read and clean the database
excel_file_path = 'DNNL DATA.xlsx'
columns_to_use = ['First Name', 'Last Name', 'Company Name']
df = pd.read_excel(excel_file_path, usecols=columns_to_use)
df = df.dropna()
df = df.reset_index(drop=True)

#Create column with full names
df['Full Name']=df['First Name'] + ' ' + df['Last Name']
display(df)

#Convert full name column to list
full_names=df['Full Name'].tolist()

#Convert elements in list to strings and remove 
#unwanted words or signs to further clean data
full_names = [str(name) for name in full_names]
remove_words = "(esdp-ic)"
full_names = [word.replace(remove_words, '') for word in full_names]

print(full_names)

    First Name   Last Name         Company Name         Full Name
0        Julia     Lemaire            Amerpodia     Julia Lemaire
1      Christa    Beaufort             ABN AMRO  Christa Beaufort
2        Rahma   el Mouden          Masdiensten   Rahma el Mouden
3         Boaz  Keurentjes          inviplay.nl   Boaz Keurentjes
4       Marijn      Kingma     Höcker Advocaten     Marijn Kingma
..         ...         ...                  ...               ...
185       Yama       Saraj  SensAi Technologies        Yama Saraj
186      Arief        Huhn          Freedomlab         Arief Huhn
187    Michael     Musandu             Lalaland   Michael Musandu
188       Kemo      Camara                 Omek       Kemo Camara
189     Stefan         Mol        Sophia Medica        Stefan Mol

[190 rows x 4 columns]

['Julia Lemaire', 'Christa Beaufort', 'Rahma el Mouden', 'Boaz Keurentjes', 'Marijn Kingma', 'Tyrell Pantophlet', 'Podiumprijs Podiumprijs', 'Nesrien Abu Ghazaleh', 'Dnbfonds Fonds', 'Virgill Olvira', 'Ammi Admin', 'Maxime De Wit', 'Nearfield Instruments  Sadeghian', 'FitFuel  De Freitas', 'Caffe Inc  Marquez', 'Caroline Williams', 'Andrea Vandijk', 'Dagmar Oudshoorn', 'Ruth Schipper', 'Suzanne Vanstraaten', 'Leroy Niemel', 'Katty Hsu', 'Dirk de Jager', 'Andre Damian', 'Edith Groenewolt', 'Timon De Leeuw', 'Annette  Atsma', 'Johnny van Doorn', 'Markus Fanselow', 'Ludger Weller', 'Ruben Halfide', 'J M Terriet', 'Yonca Braeckman', 'Chantal Heuwekemeijer', 'Danka Oosterhof', 'Steven de Lira de Lira', 'Jacqueline Van Schuppen', 'Vivian Acqua', 'Saikat Chatterjee', 'Hugo Baskoro', 'Ziaf Rehman', 'Nino Justino', 'Berkay Güres', 'Surja Bose', 'Ahmed Taskan', 'Manouk Rijper', 'Uzoma Onwudiegwu', 'Jeannine Peek', 'Chantal Korteweg', 'Hugo Westerink', 'Susan Kessing', 'Cedric Dundas', 'Edselline Jozephia', 'Paul Beiboer', 'Robbert Lut', 'Anass Meziane', 'Ronald Nieuwenhuis', 'Martin Voigt', 'Rob Defares', 'Marian Scheele', 'Alexander Ribbink', 'Christiaan Alberdingk-Thijm', 'Marian  Spier', 'Caroline  Reeders', 'Henk W. Volberda', 'Alexandra Belicova', 'Juully Ruyters', 'BEE-bestuur BEE', 'Martine Baay-Timmerman', 'Paul Disco', 'Sacha Martina', 'Rodrique Engering', 'Gail Pilgrim', 'Sanne van der Zijden', 'Paul Schmitz', 'Rick Van der Aar', 'Alice Ode', 'Chiel Griffioen', 'Gerald Vreden', 'Pim Korsten', 'Julien Nathan Balanqueux', 'Rob Hoeijmakers', 'Maya Schmucki', 'Manoj Sangany', 'Melissa Tolud', 'Oriana Bos', 'Joep Arends', 'Silvia Wiesner', 'Pieter  Waasdorp', 'Ilknur Donmez', 'Victor Chuo', 'Tyrell Pantophlet', 'Gregory van der Wiel', 'Niels Hoogland', 'Alper Tasliyurt', 'Rinke Zonneveld', 'Joris Heus', 'Ansa Wasim', 'Salmaan Sana', 'Eke Bon', 'Amily Franken', 'Lars Crama', 'Ekim Sincer', 'Marcel Kleijn', 'Charlotte Melkert', 'Mena Leila Kilani', 'Sofia Nabila Echadli', 'Dennis Pennings', 'Kay Eeftink', 'Jason Stewart', 'Ingrid Tappin', 'Aloys Langemeyer', 'Marina Lacroix', 'Anita Abaisa Abaisa', 'Kuba Knapik', 'Bruna Braga', 'Jasper Lukkezen', 'Pan Vanitcharoenthum', 'Ivo Meij', 'Mascha van Sikkelerus', 'Mackenzie Masaki', 'Peter Boerman', 'Amhar Ford', 'Nienke Aning', 'Precious Oyelade', 'Helena Garcia', 'Gina Dumfries', 'Tomàs Meulenberg', 'Carlos Van Ree', 'Qunying Liu', 'Michael Lints', 'Vincent Berkleef', 'Inge Scholman', 'Marie-Leontine De Graaf', 'Yvette Baggen', 'Femke Pluymert', 'Stephan Raes', 'Andrew Lim', 'Haroon Sheikh', 'Julia Noordergraaf', 'Jean Wagemans', 'Erik Kuisch', 'Sherida Zorg', 'Jerrol Marten', 'Caroline Kleine Staarman', 'Andy Clijnk ', 'Arjen van Witteloostuijn', 'Nancy Shenouda', 'Rishi Lodhia', 'Jerrel van Eer', 'Virgill Olvira', 'Erik-Jan Wagenmakers', 'Nelson T. Ajulo', 'Roëlla Lieveld Lieveld', 'Marieke Eestermans', 'Bart Klijsen', 'Peter Zerp Zerp', 'Gauthier Mulala', 'Erik Stam', 'Ronald Kleverlaan', 'Intelligence Forum', 'Jan Dexel', 'Menno Weij', 'Semra Celebi Celebi', 'Ruben Brave', 'Raisa Ghazi', 'Jean-Marc ter Riet', 'Michèl de Vries', 'Julia Boersma', 'Ricky Ajay Singh', 'Sander van der Waal', 'Stephane Kattie', 'Ashmita Krishna Sharma', 'Jeffery Thompson Jr', 'Marjolijn Feringa', 'Anieke Lamers', 'Gilbert Flechsig', 'Frits Bos', 'Iffat Rose Gill', 'Sharon Van Sprang', 'Sentini Grunberg', 'Niels Baay', 'Micky Chen Chen', 'Charnez Jacobs Jacobs', 'Stephan Alspeer', 'Yama Saraj', 'Arief Huhn', 'Michael Musandu', 'Kemo Camara', 'Stefan Mol']

Scrape About section

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

#open LinkedIn website
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

time.sleep(5)
driver.get("https://linkedin.com/uas/login")
time.sleep(5)

In [ ]:
#Log in
#user = "maria.baba1886@gmail.com"
#passw = "DNNLTestScraper18@"
user = "rosasalias20@gmail.com"
passw = "DNNLtest40"

username=driver.find_element(By.ID, 'username')
username.send_keys(user)
time.sleep(4)
password=driver.find_element(By.ID, 'password')
password.send_keys(passw)
time.sleep(3)
driver.find_element(By.XPATH, "//button[@type='submit']").click()

In [ ]:
#Create empty list to collect about sections

all_abouts = []

#For loop to iterate through each person
for person in full_names:
    try:
#Click on the search bar and type name
        search_bar=driver.find_element(By.CLASS_NAME, 'search-global-typeahead__input')
        search_bar.click()
        time.sleep(3)
        search_bar.send_keys(person)
        time.sleep(1)
        search_bar.send_keys(Keys.ENTER)
        time.sleep(4)

#Get profile picture
        image = driver.find_element(By.CSS_SELECTOR, 'img[src*="profile-displayphoto-shrink"]')
        image_src = image.get_attribute("src")
        time.sleep(1)
# Click on result 
        image.click()
        driver.execute_script("window.scrollBy(0, 700);")

# Locate the about section
        time.sleep(4)
        about_section = driver.find_element(By.XPATH, '//div[contains(@class, "ph5") and contains(@class, "pv3")]')
        time.sleep(3)
# Get the text content of the about section
        about_text = about_section.text
        time.sleep(4)

#Clear search bar so next name can be written
        search_bar.clear()
        all_abouts.append(about_text)

    except Exception as e:
        all_abouts.append('None')
        search_bar.clear()
#Print image sources + abouts
print(all_abouts)

In [ ]:
#Save about sections to csv file
csv_name = 'about_texts.csv'

# Write to the CSV file
with open(csv_name, 'w', newline='') as csv_file:
    csv_writer = csv.writer(csv_file)
    for x in all_abouts:
        csv_writer.writerow([x])

In [30]:
test = ['Maria Baba', 'Mika Shaham']
df_entrepreneurs = pd.DataFrame(test)

In [90]:
df_entrepreneurs = df

In [4]:
import pandas as pd
df_about = pd.read_csv('about_texts.csv', names=['About'])
merged_df = pd.merge(df_entrepreneurs, df_about, left_index=True, right_index=True, how='inner')

FileNotFoundError: [Errno 2] No such file or directory: 'about_texts.csv'

In [83]:
merged_df

,First Name,Last Name,Company Name,Full Name,About
0,Julia,Lemaire,Amerpodia,Julia Lemaire,NaN
1,Christa,Beaufort,ABN AMRO,Christa Beaufort,Leadership: able to build high performance tea...
2,Rahma,el Mouden,Masdiensten,Rahma el Mouden,Experienced Board Member with a demonstrated h...
3,Boaz,Keurentjes,inviplay.nl,Boaz Keurentjes,NaN
4,Marijn,Kingma,Höcker Advocaten,Marijn Kingma,Incisive attorney with a wide range of interes...
...,...,...,...,...,...
154,Marieke,Eestermans,Deloitte,Marieke Eestermans,"Dedicated Marketing Professional, designing & ..."
155,Bart,Klijsen,Amsterdam UMC,Bart Klijsen,Trained as Industrial Design Engineer at Delft...
156,Peter Zerp,Zerp,Accenture,Peter Zerp Zerp,I am one of the drivers of Accenture's Global ...
157,Gauthier,Mulala,O.W.N.,Gauthier Mulala,• Project management. Expertise in the managem...
158,Erik,Stam,Utrecht University,Erik Stam,NaN

In [92]:

sdg_keywords = {
    'SDG1': ['poverty', 'hunger', 'economic development', 'financial inclusion', 'unbanked', 'disaster prevention', 'microlending'],
    'SDG2': ['food security', 'agriculture', 'nutrition', 'crop yield', 'food production', 'malnutrition', 'vertical farming', 'poor nutrition', 'permaculture'],
    'SDG3': ['health', 'disease', 'well-being', 'maternal health', 'child mortality', 'vaccination', 'public health',  'prenatal care', 'road safety', 'telemedicine', 'contraception', 'antimicrobial resistance', 'elderly care'],
    'SDG4': ['literacy', 'schooling', 'access to education', 'inclusive education', 'quality education', 'universal primary education', 'equal education'],
    'SDG5': ['gender equality', 'women empowerment', 'gender-based violence', 'equal opportunities',  'AI measuring bias', 'reproductive rights', 'female health', 'underrepresented'],
    'SDG6': ['water', 'sanitation', 'hygiene', 'clean water', 'water scarcity', 'water management','safe water', 'wastewater treatment', 'water-saving', 'desalination'],
    'SDG7': ['sustainable energy', 'renewable energy', 'energy access', 'energy efficiency', 'solar energy', 'wind energy', 'tidal power', 'hydrogen'],
    'SDG8': ['employment', 'economic growth', 'decent work', 'job creation', 'labor rights', 'gender pay gap', 'equal pay', 'inclusive employment', 'fair trade'],
    'SDG9': ['sustainable industrialization', 'universal access to technology', 'inclusive industrialization'],
    'SDG10': ['inequality', 'discrimination', 'social inclusion', 'equal representation', 'fair wages'],
    'SDG11': ['urbanization', 'sustainable cities', 'resilience', 'smart cities', 'affordable housing', 'air quality measurement', 'urban waste reduction'],
    'SDG12': ['consumption', 'sustainable production', 'waste reduction', 'circular economy',  'food waste', 'sustainable fashion', 'circular', 'sustainable materials'],
    'SDG13': ['climate change', 'environment', 'carbon footprint', 'climate action', 'adaptation', 'carbon capture', 'carbon offset', 'climate tech', 'alternative protein', 'sustainable', 'sustainability'],
    'SDG14': ['oceans', 'marine life', 'conservation', 'sustainable fisheries', 'ocean pollution', 'marine conservation', 'seafood substitutes', 'overfishing', 'plastic pollution'],
    'SDG15': ['biodiversity', 'forests', 'land degradation', 'wildlife conservation', 'wildlife conservation', 'wildfires'],
    'SDG16': ['human rights', 'rule of law', 'govtech', 'digital democracy', 'corruption prevention'],
    'SDG17': ['international aid', 'sustainable development financing', 'SDG partnership'],
}

In [93]:
# Create a new column to store the matched goals
merged_df['Matched_SDGs'] = ""

# Iterate through each row and check for keyword matches
for index, row in merged_df.iterrows():
    about_text = row['About']
    if isinstance(about_text, str):
        matched_goals = [goal for goal, keywords in sdg_keywords.items() if any(keyword in about_text for keyword in keywords)]
    else:
        matched_goals = 'No goals match'

    # Update the 'Matched_Goals' column with the matched goals
    merged_df.at[index, 'Matched_SDGs'] = ', '.join(matched_goals)

merged_df.dropna(subset=['About'], inplace=True)

# Display the updated DataFrame
display(merged_df)

,First Name,Last Name,Company Name,Full Name,About,Matched_SDGs
1,Christa,Beaufort,ABN AMRO,Christa Beaufort,Leadership: able to build high performance tea...,SDG13
2,Rahma,el Mouden,Masdiensten,Rahma el Mouden,Experienced Board Member with a demonstrated h...,
4,Marijn,Kingma,Höcker Advocaten,Marijn Kingma,Incisive attorney with a wide range of interes...,SDG16
5,Tyrell,Pantophlet,Plaex Technologies,Tyrell Pantophlet,"As co-Founder, CEO & CTO of PLAEX Technologies...",SDG13
7,Nesrien,Abu Ghazaleh,Rebelmind,Nesrien Abu Ghazaleh,Social psychologist interested in how the comb...,SDG3
...,...,...,...,...,...,...
153,Roëlla Lieveld,Lieveld,Share Network,Roëlla Lieveld Lieveld,Founder & CEO at Quinky \n\n🚀 Building social ...,
154,Marieke,Eestermans,Deloitte,Marieke Eestermans,"Dedicated Marketing Professional, designing & ...",
155,Bart,Klijsen,Amsterdam UMC,Bart Klijsen,Trained as Industrial Design Engineer at Delft...,
156,Peter Zerp,Zerp,Accenture,Peter Zerp Zerp,I am one of the drivers of Accenture's Global ...,
157,Gauthier,Mulala,O.W.N.,Gauthier Mulala,• Project management. Expertise in the managem...,"SDG13, SDG15"

In [94]:
empty_counts = (merged_df['Matched_SDGs'] == '').sum()

# Display the count of empty values for each column
print(empty_counts)

70

In [96]:
merged_df.to_excel('Sustainable_development_goals_entrepreneurs.xlsx', index=False)

In [7]:
import pandas as pd
merged_df = pd.read_excel('LinkedIn/Sustainable_development_goals_entrepreneurs.xlsx')
display(merged_df)
merged_df['Matched_SDGs'] = merged_df['Matched_SDGs'].astype(str)

#View the SDGs found in the database
print(merged_df['Matched_SDGs'].unique())

#Split SDG column so each goal is on its own column in a new dataframe
merged_df = merged_df['Matched_SDGs'].str.split(',|\n', expand=True)
SDG = merged_df.stack().reset_index(level=1, drop=True).to_frame('Column')

# Remove whitespaces
SDG['Column'] = SDG['Column'].str.strip()

# Calculate total of entrepreneurs in the dataframe
total= len(SDG)

# Calculate percentages of entrepreneurs involved in the SDGs
thirteen = (SDG['Column'] == 'SDG13').sum()
f13= ((thirteen)/(total))*100
p13= round(f13)

sixteen = (SDG['Column'] == 'SDG16').sum()
f16= ((sixteen)/(total))*100
p16= round(f16)

three = (SDG['Column'] == 'SDG3').sum()
f3= ((three)/(total))*100
p3= round(f3)

two = (SDG['Column'] == 'SDG2').sum()
f2= ((two)/(total))*100
p2= round(f2)

six = (SDG['Column'] == 'SDG6').sum()
f6= ((six)/(total))*100
p6= round(f6)

five = (SDG['Column'] == 'SDG5').sum()
f5= ((five)/(total))*100
p5= round(f5)

eleven = (SDG['Column'] == 'SDG11').sum()
f11= ((eleven)/(total))*100
p11= round(f11)

twelve = (SDG['Column'] == 'SDG12').sum()
f12= ((twelve)/(total))*100
p12= round(f12)

fifteen = (SDG['Column'] == 'SDG15').sum()
f15= ((fifteen)/(total))*100
p15= round(f15)

FileNotFoundError: [Errno 2] No such file or directory: 'LinkedIn/Sustainable_development_goals_entrepreneurs.xlsx'

In [ ]:
#Plot data
import pandas as pd
import matplotlib.pyplot as plt
sdg_labels = ['SDG2', 'SDG3', 'SDG5', 'SDG6', 'SDG11', 'SDG12', 'SDG13', 'SDG15', 'SDG16']
percentages = [p2, p3, p5, p6, p11, p12, p13, p15, p16]

bar=plt.bar(sdg_labels, percentages, color=['blue', 'green', 'orange', 'red', 'purple', 'blue', 'green', 'orange', 'red', 'purple'])
plt.xlabel('Sustainable Development Goal')
plt.ylabel('Percentage')
plt.title('Distribution of SDG supported by entrepreneurs')
plt.bar_label(bar, labels=[f'{f2:.1f}%', f'{f3:.1f}%', f'{f5:.1f}%', f'{f6:.1f}%', f'{f11:.1f}%', f'{f12:.1f}%', f'{f13:.1f}%', f'{f15:.1f}%', f'{f16:.1f}%'], fontsize=12, label_type='edge')

plt.show()